### ISSUE TITLE
Build is failing

### ISSUE THREAD

**Issue by ramondelafuente** [aidmax/structurizr-cli-docker#29]
Looks like the build is failing on libssl dependencies (the release numbers have changed):

```
    libssl1.1==1.1.1k-r0 \
    libcrypto1.1==1.1.1k-r0
```

Will you tag version v0.0.4 (with structurizr 1.9.0) as the latest release?

**Comment by aidmax** [comment]
> Looks like the build is failing on libssl dependencies (the release numbers have changed):
> 
> ```
>     libssl1.1==1.1.1k-r0 \
>     libcrypto1.1==1.1.1k-r0
> ```
> 
> Will you tag version v0.0.4 (with structurizr 1.9.0) as the latest release?

@ramondelafuente it's fixed now
Sorry for inconvenience.

**Comment by ramondelafuente** [comment]
No problem, thanks for the nice work 👍
